name: Cache Docker images using GitHub Actions cache

description: |
  This GitHub Action caches Docker images using the GitHub Actions cache service. 
  It downloads the latest version of the Docker image and caches it for subsequent runs.

inputs:
  docker-image:
    description: 'The name of the Docker image to cache'
    required: true
    default: 'docker-image'
  cache-path:
    description: 'The path to the directory where the Docker image should be cached'
    required: false
    default: 'ci/cache/docker'

outputs:
  cache-hit:
    description: 'Whether the Docker image was restored from the cache'
    value: ${{ steps.cache-docker.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Get Docker image digest
      id: get-digest
      shell: bash
      run: |
        export DIGEST=$(docker image inspect --format='{{index .RepoDigests 0}}' ${{ inputs.docker-image }} | sed -E 's/^.*@//')
        export IMAGE_NAME=$(echo "${{ inputs.docker-image }}" | awk -F/ '{print $NF}')
        echo "::set-output name=digest::$DIGEST"
        echo "::set-output name=image-name::$IMAGE_NAME"        


    - name: Restore Docker image from cache
      id: cache-docker
      uses: actions/cache@v2
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ steps.get-digest.outputs.image-name }}@${{ steps.get-digest.outputs.digest }}
        restore-keys: ${{ steps.get-digest.outputs.image-name }}

    - name: Pull latest Docker image
      id: pull-image
      shell: bash
      run: |
        docker pull ${{ inputs.docker-image }}

    - name: Save Docker image to cache
      if: steps.cache-docker.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ${{ inputs.cache-path }}
        docker image save -o ${{ inputs.cache-path }}/${{ steps.get-digest.outputs.image-name }}@${{ steps.get-digest.outputs.digest }}.tar ${{ inputs.docker-image }}

#     - name: Run Docker container
#       shell: bash
#       run: docker run ${{ inputs.docker-image }}

    - name: Save cache
      if: steps.cache-docker.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ steps.get-digest.outputs.image-name }}@${{ steps.get-digest.outputs.digest }}
        restore-keys: ${{ steps.get-digest.outputs.image-name }}
